### PR TITLE
Add private_alias_method

### PR DESCRIPTION
**Pull request by tjwp**

### CODE REVIEW

**Comment by chastell** [comment]
Oh nice! Do private aliases throw a warning in older Ruby versions?

@jswanner: what do you think about adding this to private_attr?

**Comment by jswanner** [comment]
I'm fine with it. I would like to see a protected counterpart, for completeness.

Perhaps the existing tests could use some rewording, but with that said, the existing tests followed the pattern of: 
- ending with 'internally' tested private interface
- ending with 'externally' tested public interface
- ending with 'by other' tested protected interface

The tests that were added in this PR that end with 'externally' are testing the protected interface, and there are none that are testing the public interface.

**Comment by tjwp** [comment]
I've added `protected_alias_method`, including tests, and fixed the added tests as suggested.

**Comment by jswanner** [comment]
Thanks!

**Comment by chastell** [comment]
Thanks, merging! I’ll figure out the (bogus) Travis issue in the next few days and then roll the 1.2.0.

**Comment by tjwp** [comment]
Awesome, thanks!

**Pull request merged**
